grpc:
  server:
    enable-keep-alive: true
    port: 9090

spring:
  profiles:
    active: dev
  application:
    name: grpc-server
  task:
    scheduling:
      thread-name-prefix: grpc-server-task-
      pool:
        size: 2
