server:
  port: 8081

spring:
  web:
    resources:
      add-mappings: false
    #  mvc:
    #    throw-exception-if-no-handler-found: true

logging:
  level:
    io.intellij.kotlin.grpc.server.tasks.print.ClientConnPrintTask: debug